# Generated by Django 3.1.5 on 2021-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_minio_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_uploaded',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
