# Generated by Django 3.2 on 2021-05-21 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_storage', 'init_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecg_files',
            name='original_name',
            field=models.CharField(default='', help_text='Имя загруженного файла', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecg',
            name='patient_age',
            field=models.IntegerField(blank=True, help_text='Возраст пациента на момент снятия показаний(для показаний не имеющих даты рождения пациента)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
