# Generated by Django 3.1.7 on 2021-02-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_storage', '0002_auto_20210219_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecg',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата внесения в систему'),
        ),
        migrations.AlterField(
            model_name='ecg_conclusion',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата вынесения заключения'),
        ),
    ]
