# Generated by Django 3.1.7 on 2021-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_storage', '0003_auto_20210228_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_groups',
            name='description',
            field=models.TextField(blank=True, help_text='Информация о группе доступа', null=True),
        ),
    ]
