# Generated by Django 3.1.7 on 2021-03-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_storage', '0004_auto_20210228_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecg',
            name='check_date',
            field=models.DateTimeField(blank=True, help_text='Дата снятия показаний', null=True),
        ),
    ]
