# Generated by Django 3.1.7 on 2021-03-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_storage', '0006_auto_20210305_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecg_files',
            options={'ordering': ['-file_hash']},
        ),
        migrations.RemoveField(
            model_name='ecg_files',
            name='file_name',
        ),
        migrations.AddField(
            model_name='ecg_files',
            name='file_hash',
            field=models.CharField(default='', help_text='sha-1 хеш файла', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecg_files',
            name='format',
            field=models.CharField(default='', help_text='Тип файла', max_length=20),
            preserve_default=False,
        ),
    ]
